- name: download-artifact
  hosts: docker-host
  become: 'yes'
  become_user: docker-admin
  tasks:
   - name: copy the jfrog.ssh
     copy: src=/opt/app-files/jfrog.sh dest=./app-files
   - name: copy the docker file to docker host
     copy: src=/opt/app-files/Dockerfile dest=./app-files
   - name: change the permission of jfrog.ssh file
     shell: chmod 777 ./app-files/jfrog.sh
   - name: execute the jfrog.sh file
     shell: sh ./app-files/jfrog.sh
   #- name: remove all the dangling images
    # shell: echo admin | sudo -S docker rmi -f $(docker images -q)   
   - name: build the docker image
     shell: echo admin | sudo -S docker build -f ./app-files/Dockerfile --tag narsi1839/medilab-cd-app-image ./app-files/
   - name: push the docker image to docker hub
     shell: echo admin | sudo -S docker push narsi1839/medilab-cd-app-image
